### ISSUE TITLE
The Commiting System

### ISSUE THREAD

**Issue by LlamaPlays** [Flieh/diplicity-beta-feedback#10]
Following the example of Droidippy, I think there should be a commited list, to see how many people have commited. It kinda helps to see if you're the last one to commit, or just ease our anxiety on the game moving on.

**Comment by zond** [comment]
The problem is that it leads to abuse with people complaining, whining and
nagging in the chats. Is it really worth it?

**Comment by Flieh** [comment]
Here I'm with Martin. It won't be needed since you don't necessarily have to commit under the new system. You put in your orders at any point up to the deadline and you won't be considered NMR. Optionally,  you may choose to tick the ready box in the Phase Options, if everyone ticks the ready button, the turn will be adjudicated.

**Comment by Flieh** [comment]
If you're interested in fast turnaround, you can filter the games you create based on player speed. This being a mesure of how quickly a player tends to hit the ready button after each adjudication. I think I'm explaining this correctly.

**Comment by zond** [comment]
It actually only measures how often the player hit ready before timeout
happened.

On 31 Dec 2016 16:56, "Flieh" <notifications@github.com> wrote:

If you're interested in fast turnaround, you can filter the games you
create based on player speed. This being a mesure of how quickly a player
tends to hit the ready button after each adjudication. I think I'm
explaining this correctly.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Flieh/diplicity-beta-feedback/issues/10#issuecomment-269870866>,
or mute the thread
